/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class reflect4j_ReflectNative */

#ifndef _Included_reflect4j_ReflectNative
#define _Included_reflect4j_ReflectNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     reflect4j_ReflectNative
 * Method:    getReferenceById
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_reflect4j_ReflectNative_getReferenceById(JNIEnv *,
                                                                     jclass,
                                                                     jstring);

/*
 * Class:     reflect4j_ReflectNative
 * Method:    getText
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_reflect4j_ReflectNative_getText(JNIEnv *, jclass,
                                                               jint);

/*
 * Class:     reflect4j_ReflectNative
 * Method:    addComp
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_reflect4j_ReflectNative_addComp(JNIEnv *, jclass,
                                                            jint, jint);

/*
 * Class:     reflect4j_ReflectNative
 * Method:    createLabel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_reflect4j_ReflectNative_createLabel(JNIEnv *,
                                                                jclass);

/*
 * Class:     reflect4j_ReflectNative
 * Method:    setText
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_reflect4j_ReflectNative_setText(JNIEnv *, jclass,
                                                            jint, jstring);

/*
 * Class:     reflect4j_ReflectNative
 * Method:    renderComp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_reflect4j_ReflectNative_renderComp(JNIEnv *, jclass,
                                                               jint);

/*
 * Class:     reflect4j_ReflectNative
 * Method:    setSize
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_reflect4j_ReflectNative_setSize(JNIEnv *, jclass,
                                                            jint, jint, jint);

/*
 * Class:     reflect4j_ReflectNative
 * Method:    getColor
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_reflect4j_ReflectNative_getColor(JNIEnv *,
                                                                  jclass, jint);

/*
 * Class:     reflect4j_ReflectNative
 * Method:    setColor
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_reflect4j_ReflectNative_setColor(JNIEnv *, jclass,
                                                             jint, jint, jint,
                                                             jint);

/*
 * Class:     reflect4j_ReflectNative
 * Method:    setVisible
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_reflect4j_ReflectNative_setVisible__IZ(JNIEnv *,
                                                                   jclass, jint,
                                                                   jboolean);

/*
 * Class:     reflect4j_ReflectNative
 * Method:    setVisible
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_reflect4j_ReflectNative_setVisible__II(JNIEnv *,
                                                                   jclass, jint,
                                                                   jint);

#ifdef __cplusplus
}
#endif
#endif
